version: '3'
services:
  redis-rejson:
    image: redislabs/rejson
    container_name: redis
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "6379:6379"
    networks:
      - redis
    volumes:
      - redis-data:/data
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

volumes:
  redis-data:
networks:
  redis: