version: "3"
services:
  redis:
    image: redis/redis-stack:6.2.2-v5
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"
  redis-pass:
    image: redis/redis-stack:6.2.2-v5
    container_name: "redis-pass"
    restart: always
    environment:
      - "REDIS_ARGS=--requirepass s3cret"
    ports:
      - "6380:6379"
