version: '3'
services:
  redis:
    image: redislabs/rejson:2.0.6
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"
  redis-pass:
    image: bitnami/redis:6.2.6
    container_name: "redis-pass"
    restart: always
    environment:
      - "REDIS_PASSWORD=s3cret"
    ports:
      - "6380:6379"